





const Database = 
    [
        {
            imagen:"../productos/UspKillConfirmed.png",
            float: 'Minimal Wear',
            producto: 'Usp KillConfirmed',
            stock: "si",
            stattrack:"no",
            precio: "$"+13000,
            categoria:"pistola",
        },
        {
            imagen:"../productos/Ak47BloodSport.png",
            float: 'Factory New',
            producto: 'Ak-47 BloodSport',
            stattrack:"no",
            stock: "si",
            precio: "$"+20000,
            categoria:"rifle",
        },
        {
            imagen:"../productos/AwpAtheris.png",
            float: 'Minimal Wear',
            producto: 'Awp Atheris',
            stattrack:"no",
            stock: "si",
            precio: "$"+5000,
            categoria:"sniper",
        },
        {
            imagen:"../productos/AwpDragonFire.png",
            float: 'Battle Scarred',
            producto: 'Awp WildFire',
            stattrack:"no",
            stock: "si",
            precio: "$"+3500,
            categoria:"sniper",
        },
        {
            imagen:"../productos/AwpFade.png",
            float: 'Factory New',
            producto: 'Awp Fade',
            stattrack:"no",
            stock: "no",
            precio: "$"+150000,
            categoria:"sniper",
        },
        {
            imagen:"../productos/AwpGugnir.png",
            float: 'Minimal Wear',
            producto: 'Awp Gugnir',
            stattrack:"no",
            stock: "no",
            precio: "$"+700000,
            categoria:"sniper",
        },
        {
            imagen:"../productos/BowieLore.png",
            float: 'Factory Newr',
            producto: 'Bowie Lore',
            stattrack:"no",
            stock: "no",
            precio: "$"+40000,
            categoria:"cuchillo",
        },
        {
            imagen:"../productos/MotoGlovesPolygon.png",
            float: 'Well Worn',
            producto: 'MotoGloves Polygon',
            stattrack:"no",
            stock: "si",
            precio: "$"+47000,
            categoria:"guantes",
        },
        {
            imagen:"../productos/CrimsonKimonoGloves.png",
            float: 'Well Worn',
            producto: 'Crimson Kimono',
            stattrack:"no",
            stock: "no",
            precio: "$"+70000,
            categoria:"guantes",
        },
        {
            imagen:"../productos/Estileto.png",
            float: 'Minimal Wear',
            producto: 'Estileto Tiger Thoot',
            stattrack:"no",
            stock: "si",
            precio: "$"+45000,
            categoria:"cuchillo",
        },
        {
            imagen:"../productos/UspMonster.png",
            float: 'Factory New',
            producto: 'Usp MonsterMashup',
            stattrack:"no",
            stock: "si",
            precio: "$"+8000,
            categoria:"pistola",
        },
        {
            imagen:"../productos/UmpBlaze.png",
            float: 'Factory New',
            producto: 'Ump Blaze',
            stattrack:"si",
            stock: "no",
            precio: "$"+9000,
            categoria:"subfusil",
        },
        {
            imagen:"../productos/GlockBulletQueen.png",
            float: 'Well Worn',
            producto: 'Glock BulletQueen',
            stattrack:"no",
            stock: "si",
            precio: "$"+3500,
            categoria:"pistola",
        },
        {
            imagen:"../productos/M4A1PrintStream.png",
            float: 'Minimal Wear',
            producto: 'M4-A1 PrintStream',
            stattrack:"no",
            stock: "no",
            precio: "$"+45000,
            categoria:"rifle",
        },
        {
            imagen:"../productos/GlockVogue.png",
            float: 'Well Worn',
            producto: 'Glock Vogue',
            stattrack:"no",
            stock: "no",
            precio: "$"+8700,
            categoria:"pistola",
        },
        {
            imagen:"../productos/GutKnife.png",
            float: 'Factory New',
            producto: 'Gut Knife',
            stattrack:"si",
            stock: "no",
            precio: "$"+110000,
            categoria:"cuchillo",
        },
        {
            imagen:"../productos/Mariposa.png",
            float: 'Minimal Wear',
            producto: 'Mariposa Fade',
            stattrack:"no",
            stock: "no",
            precio: "$"+570000,
            categoria:"cuchillo",
        },
        {
            imagen:"../productos/MotoGlovesTurtle.png",
            float: 'Batlle Scarred',
            producto: 'MotoGloves Turtle',
            stattrack:"no",
            stock: "si",
            precio: "$"+50000,
            categoria:"guantes",
        },
        {
            imagen:"../productos/M4A1BlueFosfore.png",
            float: 'Minimal Wear',
            producto: 'M4-A1 Blue Fosfore',
            stattrack:"no",
            stock: "no",
            precio: "$"+170000,
            categoria:"rifle",
        },
        {
            imagen:"../productos/Navaja.png",
            float: 'Factory New',
            producto: 'Navaja Tiger Thoot',
            stattrack:"no",
            stock: "no",
            precio: "$"+90000,
            categoria:"cuchillo",
        },
        {
            imagen:"../productos/M4A4Emperador.png",
            float: 'Battle Scarred',
            producto: 'M4-A4 Emperador',
            stattrack:"no",
            stock: "si",
            precio: "$"+13000,
            categoria:"rifle",
        },
        {
            imagen:"../productos/M4A4LivingColor.png",
            float: 'Factory New',
            producto: 'M4-A4 Living Color',
            stattrack:"no",
            stock: "si",
            precio: "$"+6000,
            categoria:"rifle",
        },
        {
            imagen:"../productos/PandoraGloves.png",
            float: 'Minimal Wear',
            producto: 'Pandora Gloves',
            stattrack:"no",
            stock: "no",
            precio: "$"+300000,
            categoria:"guantes",
        },
    ]

export default Database



